[package]
name = "dualoj-judge"
version = "0.1.0"
authors = ["zLeoAlex <z.alex.leo@outlook.com>"]
edition = "2018"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
tokio = { version = "1.4.0", features = ["full"] }
futures = "0.3.13"
serde_json = "1.0.64"

# Data transfer between server & client
tonic = { version = "0.4.1", features = ["tls"] }
prost = "0.7.0"
prost-types = "0.7.0"

# Some async support
async-trait = "0.1.48"

# CLI support
structopt = "0.3.21"

# Archive support
tar = "0.4.33"

# Server Log support
log = "0.4.14"
pretty_env_logger = "0.4.0"

# Archive image management
uuid = { version = "0.8.2", features = ["v5"] }

[build-dependencies]
tonic-build = "0.4.1"
