# syntax = denzp/cargo-wharf-frontend:v0.1.0-alpha.2

[package]
name = "dualoj-judge"
version = "0.1.0"
authors = ["zLeoAlex <z.alex.leo@outlook.com>"]
edition = "2018"
default-run = "server"

[package.metadata.wharf.builder]
image = "docker.io/clux/muslrust:nightly-2021-04-23"
target = "x86_64-unknown-linux-musl"

[package.metadata.wharf.output]
image = "docker.io/library/alpine:3.13"
post-install-commands = [
  { shell = "apk add --no-cache libgcc", display = "Installing runtime dependencies" },
]
entrypoint = ["/bin/server"]

[[package.metadata.wharf.binary]]
name = "server"
destination = "/bin/server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
tokio = { version = "1.4.0", features = ["full"] }
futures = "0.3.13"
serde_json = "1.0.64"

pretty_env_logger = "*"

# For Invoke buildkit tools
buildkit-frontend = "0.3.0"
buildkit-llb = "0.2.0"

# Data transfer between server & client
tonic = "0.4.1"
prost = "0.7.0"

# Some async support
async-trait = "0.1.48"
failure = "0.1.8"

[build-dependencies]
tonic-build = "0.4.1"
