[package]
name = "dualoj-judge"
version = "0.1.0"
authors = ["zLeoAlex <z.alex.leo@outlook.com>"]
edition = "2018"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
tokio = { version = "1.4.0", features = ["full"] }
futures = "0.3.13"
serde_json = "1.0.64"

pretty_env_logger = "*"

# For Invoke buildkit tools
buildkit-frontend = "0.3.0"
buildkit-llb = "0.2.0"

# Data transfer between server & client
tonic = { version = "0.4.1", features = ["tls"] }
prost = "0.7.0"

# Some async support
async-trait = "0.1.48"

# CLI support
structopt = "0.3.21"

[build-dependencies]
tonic-build = "0.4.1"
