# syntax = denzp/cargo-wharf-frontend:v0.1.0-alpha.2

[package]
name = "dualoj-judge"
version = "0.1.0"
authors = ["zLeoAlex <z.alex.leo@outlook.com>"]
edition = "2018"
default-run = "server"

[package.metadata.wharf.builder]
image = "docker.io/clux/muslrust:nightly-2021-04-23"
target = "x86_64-unknown-linux-musl"

[package.metadata.wharf.output]
image = "docker.io/library/alpine:3.13"
post-install-commands = [
  { shell = "apk add --no-cache libgcc", display = "Installing runtime dependencies" },
]
entrypoint = ["/bin/server"]

[[package.metadata.wharf.binary]]
name = "server"
destination = "/bin/server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
tokio = { version = "1", features = ["full"] }
futures = "*"
serde_json = "*"
serde = "*"

pretty_env_logger = "*"

# For Web backend
rocket = "0.4.7"

# For Invoke buildkit tools
buildkit-frontend = "*"
buildkit-llb = "*"
tonic = "*"

# Some async support
async-trait = "*"
failure = "*"
