apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dualoj
  name: build-machine
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/attach", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
