apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dualoj
  name: build-machine
rules:
  - apiGroups: ["rbac.authorization.k8s.io", ""]
    resources: ["pods", "jobs"]
    verbs: ["get", "list", "watch", "create"]
