apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: dualoj
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: docker.io/library/registry:2.7.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: dualoj
spec:
  selector:
    app: registry
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: dualoj
  labels:
    name: registry-ingress
spec:
  rules:
    - host: registry.dualoj.svc.cluster.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: registry
                port:
                  number: 80
  tls:
    - secretName: registry-ingress
      hosts:
        - "registry.dualoj.svc.cluster.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: dualoj
data:
  registry-url: registry.dualoj.svc.cluster.local # Config judger to use local registry
