apiVersion: apps/v1
kind: Deployment
metadata:
  name: judger
  namespace: dualoj
spec:
  selector:
    matchLabels:
      app: judger
  template:
    metadata:
      labels:
        app: judger
    spec:
      serviceAccountName: judger
      containers:
        - name: judger
          image: localhost/dualoj-judge:demo
          envFrom:
            - configMapRef:
                name: registry-config
            - configMapRef:
                name: buildkitd-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: judger-certs
---
apiVersion: v1
kind: Service
metadata:
  name: judger
  namespace: dualoj
spec:
  selector:
    app: judger
  ports:
    - port: 80
      name: http
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judger
  namespace: dualoj
  labels:
    name: judger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /judger(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: judger
                port:
                  name: http
