apiVersion: apps/v1
kind: Deployment
metadata:
  name: judger
  namespace: dualoj
spec:
  selector:
    matchLabels:
      app: judger
  template:
    metadata:
      labels:
        app: judger
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: judger-account
      containers:
        - name: judger
          image: localhost/dualoj-judge:demo
          env:
            - name: RUST_LOG
              value: debug
            - name: SIZE_LIMIT
              value: "50000000"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONTROLLER_PORT
              value: "50051"
            - name: JUDGER_PORT
              value: "80"
          envFrom:
            - configMapRef:
                name: registry-config
            - configMapRef:
                name: buildkitd-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "[ $(echo 'helloworld' | client --addr grpc://${POD_IP}:50051 echo) = 'helloworld' ]"
          ports:
            - containerPort: 50051
              name: controller
            - containerPort: 80
              name: judge-server
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: judger-certs
---
apiVersion: v1
kind: Service
metadata:
  name: judger-judge
  namespace: dualoj
spec:
  selector:
    app: judger
  ports:
    - port: 80
      targetPort: judge-server
---
apiVersion: v1
kind: Service
metadata:
  name: judger-controller
  namespace: dualoj
spec:
  type: NodePort
  selector:
    app: judger
  ports:
    - port: 50051
      name: grpc
      targetPort: controller
