apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fork-builder
  namespace: dualoj
subjects:
  - kind: ServiceAccount
    name: judger
    namespace: dualoj
roleRef:
  kind: Role
  name: build-machine
  apiGroup: rbac.authorization.k8s.io
